// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:7e1701b8-8c86-4b41-a9d5-c46d590297c0',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsvueamplify-hosting-mobilehub-554487989',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1xwoollk1fdnh.cloudfront.net',
    'aws_mobile_analytics_app_id': '5fd5b25c8960425d8a70f92ed390a4dc',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '9cae5bbe-a96e-4d79-a7a4-7192c84129cb',
    'aws_project_name': 'aws-vue-amplify',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'awsvueamplify-mobilehub-554487989',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'awsvueamplify-userfiles-mobilehub-554487989',
    'aws_user_files_s3_bucket_region': 'eu-west-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-1_p34envlRJ',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '3bepsh93qgocg6458j6abpbpig',
}

export default awsmobile;
